name: Pre-commit hooks

on:
    pull_request:
    push:
      branches:
        - main

jobs:
  pre-commit-hooks:
    runs-on: [os-medium-amd64-linux]
    permissions: 
        contents: read
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: '3.12'
              check-latest: false
              update-environment: true
              allow-prereleases: false

        - name: Upgrade pip
          run: python -m pip install --upgrade pip
        
        - name: Install pre-commit
          run: 
              pip install pre-commit
              
        - name: Run pre-commit hooks
          run: pre-commit run --all-files