# This is a basic workflow to help you get started with Actions

name: Create GKE With Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  create-gke:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: gke-cluster

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/399757394151/locations/global/workloadIdentityPools/gke-test-action/providers/github
          service_account: git-hub-action@my-project-3bd1e.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Run terraform init
        run: terraform init

      - name: Run terraform validate
        run: terraform validate

      - name: Run terraform apply
        run: terraform apply -no-color -auto-approve
